### PR TITLE
pd/feat/task#1

### PR DESCRIPTION
**Pull request by YARE0909**
# Create a new file and added some basic ts code!

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by shawshankkumar** [comment]
PR name and file name should be different. Create is better than created.

**Comment by kevinaaaquil** [comment]
create a branch with proper naming convention and make a pr, not from your main branch

**Comment by YARE0909** [comment]
> create a branch with proper naming convention and make a pr, not from your main branch

Ok so i should create a new branch in my fork and then create a pull request from that?

**Comment by kevinaaaquil** [comment]
> > create a branch with proper naming convention and make a pr, not from your main branch
> 
> Ok so i should create a new branch in my fork and then create a pull request from that?

that should work :)

**Comment by YARE0909** [comment]
> > > create a branch with proper naming convention and make a pr, not from your main branch
> > 
> > Ok so i should create a new branch in my fork and then create a pull request from that?
> 
> that should work :)
> 

Alr will do thank you😁

**Comment by kevinaaaquil** [comment]
great

**Pull request closed without merging**
