### PR TITLE
A basic `hello world` server implementation 

### PR DESCRIPTION
**Pull request by jatindotdev**
# Description
A basic http server implementation in node.js which sends a basic message as response

# Changes made
* [x] implemented boilerplate code for node http server

### CODE REVIEW

**Comment by shawshankkumar** [comment]
Use the proper template for PR and use proper commit names.

**Comment by shawshankkumar** [comment]
PR name should be different from branch name.

**Comment by jatindotdev** [comment]
> Use the proper template for PR and use proper commit names.

noted! so should i create a new pr or take care of it next time

Thanks!

**Comment by kevinaaaquil** [comment]
create a branch with proper naming convention and make a pr, not from your main branch

**Comment by jatindotdev** [comment]
> create a branch with proper naming convention and make a pr, not from your main branch

okay 👍

**Pull request closed without merging**
