### PR TITLE
Task from Harsh Patel

### PR DESCRIPTION
**Pull request by HarshPatel5940**
# Description

## The meeting was fun

### CODE REVIEW

**Comment by shawshankkumar** [comment]
Check the previously closed pr. File name should not have spaces.

**Comment by HarshPatel5940** [comment]
oh ok, fixing it

**Comment by HarshPatel5940** [comment]
I have updated the file name 👍

**Comment by kevinaaaquil** [comment]
traditionally we use a file naming convention called camelCase which looks something like this -> harshPatel.txt
also hp/feat/ -> this should proceed the task that you did. like hp/feat/addFile

**Comment by HarshPatel5940** [comment]
@Kevin-Aaaquil should re open the PR or is it fine?

**Comment by kevinaaaquil** [comment]
close and make a new one

**Comment by HarshPatel5940** [comment]
Mhmm

**Comment by shawshankkumar** [comment]
snake case is also fine. hello_world.py

**Pull request closed without merging**
